# Site settings
name: VidCoder
email: 
author: RandomEngy

keywords: blu-ray, rip, video, handbrake, encoding, transcoding
description: > # this means to ignore newlines until "baseurl:"
  VidCoder is an open-source DVD/Blu-ray ripping and video transcoding application for Windows. It uses HandBrake as its encoding engine.

baseurl: ""
#baseurl: /VidCoder
#url: https://vidcoder.net/

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]

# Header
header: yes
header_xl: images/BannerLarge.png

# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto
